### ISSUE TITLE
auth problem step 4

### ISSUE THREAD

**Issue by timur87** [eouia/MMM-GAction#1]
Hi there
i have a problem with step 4
If I do this and the browser is opened where I can select my account, the following message from google comes up:

Registration with Google is temporarily deactivated for this app
The use of Google Log-in has not yet been confirmed for this app.

**Comment by eouia** [comment]
I think it could be a temporary issue, but if this takes a long, I'll inspect.

**Comment by timur87** [comment]
do i have another possibility to do the auth temporarily? would like to use it

**Comment by eouia** [comment]
Exactly which step do you have an issue on? 
I tested now on my macbook, it worked (At this moment, I have no RPI to test. It will take a while)
![image](https://user-images.githubusercontent.com/1720610/76638656-1a848100-654d-11ea-9704-c11b733314c9.png)
If you select your account, consent screen should be displayed, but instead did you meet the message? Your project seems to be not setup properly.

**Comment by timur87** [comment]
exactly at step 4

for me on the rpi I have to enter ./gactions login

then there is a page with google accounts i choose the right account and then the message comes from the first post above

**Comment by eouia** [comment]
? 
./gactions login is not needed.

**Comment by timur87** [comment]
when I run 

./gactions update --action_package actions.json --project [YOUR PROJECT_ID] 

I get the message from rpi:
Error: Not logged in. Please run `gactions login` to login.

**Comment by eouia** [comment]
Try this;
```
./gactions --help
or 
./gactions -h
or
./gactions --version
or
./gactions -V
```
To check version. (I'm not sure which will work), The current version will be around 2.2.4

I've heard `gactions cli` for RPI is not updated any more.  If so, use gactions in another dev-machine like OSX or any Linux. (or Windows)
It has no need to be done on RPI.

**Comment by timur87** [comment]
none of these commands work ...

`Usage:
  gactions [flags]
  gactions [command]

Available Commands:
  channel     Display current or set new release channel for gactions.
  deploy      Deploy Action's fulfillment, NLU and console configuration.
  download    Download a Actions on Google sample.
  get         Get the contents of a given version of your Action.
  help        Help about any command
  init        Initialize a new project.
  list        List up to 10 recent versions of your app for the Assistant and their status.
  login       Login to gactions.
  logout      Log out of gactions.
  open        Open a Actions on Google related product.
  project     Display current or set new Google Project ID.
  selfupdate  This command will check for updates and perform a in-place upgrade if an update if found.
  test        Takes the specified Action for the Assistant and makes it available for previewing/simulation.
  update      Updates the draft action in the app for the Assistant for the given project.
  version     Prints the version of gactions.

Flags:
  -h, --help      help for gactions
  -v, --verbose   verbose output

Use "gactions [command] --help" for more information about a command.

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x55cf68]

goroutine 1 [running]:
github.com/actions-on-google/gactions/commands.Execute()
	/Users/matthewcarroll/dev/actions-on-google/cli/commands/root.go:54 +0x88
main.main()
	/Users/matthewcarroll/dev/actions-on-google/cli/main.go:24 +0x14
`

but once i had the right command through google and i remember that my version was 2.2.2

how can i do this step with windows 10?

**Comment by eouia** [comment]
Sorry, I haven’t used windows in 10years. have no idea

**Comment by timur87** [comment]
So I've now used vmbox to set up unbuntu.
Then I carried out steps 4 and 5 on unbuntu, then a new file was created called "creds.data" which I then transferred to the magic mirror, then I simply included gaction in the config and restarted mm but somehow nothing happens if when I say "turn mirror off" ...

**Comment by eouia** [comment]
Google action is not related with Amk2 module itself. You don’t need any interaction with amk2 module to make action.
When your action is registered even in other machine, the next thing would be to make a recipe to be triggered by that action.

**Comment by eouia** [comment]
Can you show me your Action file?

**Comment by timur87** [comment]
I use the action.json without any changes and as a recipe I integrated the Reboot-Restart-Shutdown.js into the config to test whether it works

**Comment by eouia** [comment]
Reboot-Restart-Shutdown.js is not for action but for transcriptionHook.


Ok. I'm assuming your success to step 5 with default `actions.json`.
You might have this message on step 5. 
![image](https://user-images.githubusercontent.com/1720610/76704213-ae825400-66d7-11ea-96e7-ea6461eb9bed.png)

Now you need to make `command` for that action.
Make your recipe file `test.js` like this;
```js
var recipe = {
  commands: {
    "com.example.commands.REBOOT": {
      notificationExec: {
        notification: "SHOW_ALERT",
        payload: {
          title: "GACTION Test",
          timer: 3000,
        }
      }
    }
  }
}

exports.recipe = recipe // Don't remove this line.
```
This command means when `com.example.commands.REBOOT`(defined in actions.json as command name) is triggered, do this stuff (emitting notification).

and then, load this recipe in your AMK2 config.
```js
recipes: ["with-MMM-Hotword.js", ... , "test.js"],
```

Then, execute MM, say `reboot now` and you can get this, if everything is ok.

Result: 
![image](https://user-images.githubusercontent.com/1720610/76704202-90b4ef00-66d7-11ea-96d5-c4adfd93b31f.png)

**Comment by eouia** [comment]
You can check whether action is activated or not by `debug:true`, The `ASSISTANT_RESULT` log will have action object like this;
```js
[16:08:39.552] [LOG]    [AMK2] ASSISTANT_RESULT { session: 1584284918257,
  transcription: { transcription: 'reboot now', done: true },
  action:
   { requestId: '5e703394-0000-28e6-8e9b-3c286d3f44b2',
     inputs: [ [Object] ] },
  screen:
   { links: [],
     text:
      'Here\'s the result from Magic Mirror Controller.\nYour Mirror will be rebooted, My lord.',
...
```
`action` object will have `inputs` object.

But with normal query (not triggered), `action` object won't have `inputs` object.
```js
[16:07:58.246] [LOG]    [AMK2] ASSISTANT_RESULT { session: 1584284876434,
  transcription: { transcription: 'what time is it?', done: true },
  action: { requestId: '5e70397e-0000-277f-a7d2-3c286d41870a' },
  screen:
   { links: [],
     text:
      'London, UK / Local Time\n15:07\nSunday, 15 March 2020\nTime in London, UK',
```

**Comment by timur87** [comment]
do you still have telegram? I think communication would be much easier

**Comment by eouia** [comment]
Feel free to contact.

**Comment by timur87** [comment]
where can I find your telegram account details?

**Comment by eouia** [comment]
@eouia

**Comment by timur87** [comment]
For everyone who reads this.

I was the mistake not the module the module works well!
